### ISSUE TITLE
Server not run

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [RocketFoundation/Rocket#184]
After rollback from 9.1 to 8.5 server refuses to run giving error in console
here is screenshot http://s014.radikal.ru/i327/1506/e0/3e2d892429e4.jpg

**Comment by Ammodex** [comment]
Братка, такая же проблема! I have the same issue

**Comment by fr34kyn01535** [comment]
https://github.com/RocketFoundation/Rocket/wiki/Fixing-Issues

**Comment by darkscissors** [comment]
How do you solve this, I have tried running it in a clean server setup and get the same error after downloading all necessary files.

**Comment by crook47** [comment]
He links to something completely irrelevant to your problem, doesn't surprise me.

**Comment by fr34kyn01535** [comment]
I dont think that the guide on how to fix issues with Uturned is irelevant for people with issues with Unturned, but it is no surprise to me that you didnt bother to read it.

**Comment by fr34kyn01535** [comment]
Btw, @crook47, better read that guide yourself, it could fix your generator problem.

**Comment by crook47** [comment]
I read it. But that guide is completely irrelevant to his issue. Along with mine.

**Comment by crook47** [comment]
And I didn't sort it myself, still an issue bet since you're so super smart it's not and issue at all so I just closed it.

**Comment by Zamirathe** [comment]
From the error, it is trying to load in the Rocket asset which isn't in 3.10.8.5.  Please follow the steps at the bottom of the guide fr34ky posted under "None of the solutions above fixed my problem".  Please note what the results were at each stage.  This way it helps to pinpoint where the issue is starting.

Note, to test this, do a complete clean install.  That means rename/delete your map, level, players, everything related to the server.  No workshop items, no Rocket, no plugins, nada to test in Vanilla.  Just reinstalling Rocket but keeping everything else there doesn't help determine where issues start.

@crook47 It is completely relevant.  Read the last paragraph and mine above.  If detailed information is not provided, one can not expect someone else to understand what the problem is, let alone find it.
