### ISSUE TITLE
Game buttons disabled

### ISSUE THREAD

**Issue by trivera90** [RocketFoundation/Rocket#2]
I cant seem to press any of the buttons in game while running the server on the same machine. Game buttons work after i uninstall rocket. Please help!

**Comment by trivera90** [comment]
the only error i get is corrupt resource.assets file

**Comment by fr34kyn01535** [comment]
You should not patch the game you play with. Rocket is a server mod and should be installed on seperate dedicated servers. Follow the instructions on https://rocket.foundation/get-rocket/ to find out how to setup this. I guess to fix it you need to repair the game over Steam.

**Comment by trivera90** [comment]
i dont have another dedicated machine to run the server on. So this mod is only for dedicated servers? Do you know of any other mods i can install and play on the same machine?

**Comment by MasterCreate66** [comment]
Check this out: https://developer.valvesoftware.com/wiki/SteamCMD

You can use the following script to setup a dedicated Unturned server::
steamcmd.exe +login (Steam Username) (Steam Password) +force_install_dir ../Unturned +app_update 304930 -beta preview -betapassword OPERATIONMAPLELEAF validate  +exit

Just open notepad, paste that in, select all files instead of .txt files and than name is update.bat

**Comment by trivera90** [comment]
Thanks Guys!! Got it working!!
