### ISSUE TITLE
Rocket #534 broke my plugin.

### ISSUE THREAD

**Issue by DevLeeo** [RocketFoundation/Rocket#467]
I have updated my plugin to rocket 4.6 (#534) and...

![image](https://cloud.githubusercontent.com/assets/10111205/8895418/eaddfcac-33af-11e5-8e9e-607e52ee0929.png)

![image](https://cloud.githubusercontent.com/assets/10111205/8895419/f04163b4-33af-11e5-8ebd-2c7acf6d5e4d.png)

**Comment by Kirollos** [comment]
"I am sorry, but as always, with progress, old things will break. I will try to update my plugins as fast as i can and support the developers that want to update, i can't help if other developers don't update their plugins tho. Make sure to find out if eventual issues are caused by outdated plugins before submitting bug reports. A few core features were removed as i didn't like their implementation"

https://rocket.foundation/viewtopic.php?f=44&t=706

**Comment by DevLeeo** [comment]
I have updated ...

**Comment by DevLeeo** [comment]
Close!

I added wrong dll references... sorry...
