### ISSUE TITLE
Lag bug

### ISSUE THREAD

**Issue by h4ugen** [RocketFoundation/Rocket#71]
All players on the server suddenly have 300 + their normal ping.
So, my ping is 45, so it suddenly turns to 345.

When I run multiple servers the ping bug might only occur on one, but not the other server.
Goes down to normal when the server is restarted..

Searched abit it seems someone else had the same problem
http://www.reddit.com/r/unturned/comments/301cj1/unturned_3855_high_ping_bug/

That's all!

**Comment by falsechicken** [comment]
I am not sure this is a problem with Rocket. The Reddit post you referred to seems to be talking about vanilla Unturned. Rocket is not mentioned. 

I know that I need to restart my server about every 45 minutes to an hour or the ping gets so high it becomes unplayable. With or without Rocket installed.

**Comment by h4ugen** [comment]
Ah so it's an unturned bug then, alright thanks.

**Comment by falsechicken** [comment]
Np. I believe this can be closed now lol. Thanks for participating anyway.

**Comment by fr34kyn01535** [comment]
Not a Unturned bug at all, your computer can't simply handle it.

**Comment by falsechicken** [comment]
Really? Interesting. My server runs the notoriously heavy Minecraft server just fine but struggles when Unturned runs for more than 45 minutes. No matter how many players are online, the lag still happens. Its predictable. I thought that was the reason so many servers have automatic restart plugins. To reduce the lag "build up".

**Comment by fr34kyn01535** [comment]
Afaik Rocket doesn't get slower / Restarts don't fix anything. I run the servers just fine without lags, whats the difference between you and me? Right, the machine.

**Comment by manuelbarbosa** [comment]
Actually this is a issue fr34k despite your server showing a 30 PING in the server list, when you actually log to them the ping goes all the way up to 400. Same happens in my server even in my home network. This is actually a unturned / steam servers issue.

You don't know about this because you don't actually log that much in your own servers you just check the server status via the server list that shows a misleading PING information (last time you logged with me in one of your servers you couldn't even establish a connection, I have the same problem in my server if I don't restart them)

**Comment by falsechicken** [comment]
Yeah. My ping is always low on the server list. But when in game it seems to be a different story.

**Comment by Hammereditor** [comment]
Yes, I have seen this problem for over two months on all HammerHost servers. But I don't know whose fault it is.

**Comment by Zamirathe** [comment]
Has anyone looked at how much was the on the map when this happens?  Is that a factor?

**Comment by cartman-2000** [comment]
The amount of stuff on the map doesn't really matter all that much, what seems to matter for me is if the server is a PVE one or a PVP one, the PVP server that I run always gets to a laggy state faster than the PVE one. The PVE one can run fine for a few hours or so, but the PVP one would need to be restarted every hour to three hours otherwise most of the players on it are getting pings at or above 300ms(with the TPS running at 3 on the server most of the time at that point.). At the current moment in time the PVP server's map data files are some 4-5 times smaller than the PVE server's ones.

**Comment by Hammereditor** [comment]
Can you tell us what happens if you make the PvE server PVP, and the PvP server PvE?

**Comment by Kameron1** [comment]
Large amounts of lag

**Comment by Kameron1** [comment]
Also invisible players. They are invisible to eachother

**Comment by Kameron1** [comment]
Also invisible players hoping its a bug not a problem with my server!

**Comment by h4ugen** [comment]
Screenshot shows two different servers running at the same time.
Also, when the ping bug occurs, typing in the server console is laggy aswell, it takes ages
for the text to pop up on the screen.

On the one server their ping is stuck on 207 - 209
On the other one everything is just fine.

http://i.imgur.com/lLZ5mth.png

**Comment by Kameron1** [comment]
True^^

**Comment by falsechicken** [comment]
Indeed. I too have noticed the console lag. It can get pretty bad. Before I had Rocket I would use AutoHotkey to automatically shut down the server. It was amusing watching every individual keystroke xD.

**Comment by Hammereditor** [comment]
Yes, I also used Autohotkey. Remember that if typing into the console window is choppy, the server is probably lagging.

**Comment by falsechicken** [comment]
^ Yeah that was a pretty good lag indicator for me as well.

**Comment by cartman-2000** [comment]
And the minimum TPS the lag command will show is 3 TPS, but it can be worse than that at times depending on how long the server has been running. It can take up to 5 seconds to printout the command shutdown sometimes.

**Comment by h4ugen** [comment]
I know I've posted examples before, but heres another interesting one!
http://i.imgur.com/rPv7ZVs.png
Look how everyones ping is 314, except for two players who has 312 and 313. Weird!

**Comment by Hammereditor** [comment]
You forgot "311" and "490".

**Comment by falsechicken** [comment]
Yeah. That is intersting thought. I wonder whats up with that. Either the planets aligned and almost everyone has the same ping or something funny is happening xD.

**Comment by Ev1dentFir3** [comment]
I find the larger my saved player list gets, the more my server lags. Also doing monthly wipes helps a lot too. But the high ping is an issue since the beginning.

Things that can help:
- Make sure databases are on the localhost
- Set your server timeout a little lower, so that one player in China cant connect and slow everyone else down.
- Check the server memory usage, try removing plugins that are heavy on the server. Plugins use memory, and some might not recover memory properly if coded by someone new to programming.
- Turn off features you don't use, (Rcon for example)

**Comment by Hammereditor** [comment]
3.10.x.x was the golden age of performance. But how can a player with high latency increase the latency for other players? The Unity engine can't possible be this buggy.

**Comment by Ev1dentFir3** [comment]
Unturned defaults to 15 ticks (state updates) a second, and a person with lag causes the server to not receive all of the clients ticks which gives them that jitter you see when you accuse a high ping player of hacking lol. Also it causes their game experience to be shit also as they rubber band like crazy, or headshot but don't kill a player.

And when a server is dealing with choppy information it can sometimes stop a code thread dead if a specific response is needed from the laggy client, and it takes the better part of a second or two to receive an answer.

 The server can't update you where that player is until it knows where he is :-p

**Comment by fr34kyn01535** [comment]
MySQL connection speed has nothing to do with lags, devs should code async. High pings are not slowing anybody down nor affecting server performance, they simply have people lagging. High memory usuage is not a problem, unless its a leak. Turning RCON off will NOT affect server performance. The story with the ticks not being all received is not even making sense, but sure, if people have a bad connection they lag - thats not new and makes sense to everybody. Ticks is not state updates.

**Comment by Ev1dentFir3** [comment]
EVERYTHING your server is doing is using some resources, and yes having a MYSQL server on the same box as your server is lag reduction 101, Google it. If a MYSQL has high ping then the server has to wait for a response from it before it can apply that response to a player.


As for tickrate during each tick, the server processes incoming user commands, runs a physical simulation step, checks the game rules, and updates all object states. After simulating a tick, the server decides if any client needs a world update and takes a snapshot of the current world state if necessary. A higher tickrate increases the simulation precision, but also requires more CPU power and available bandwidth on both server and client.

Sorry if calling all that a "server state update" was to small a word but just trying to keep things simple.

But hey, I forgot I'm not a game dev so I must not know anything about this...

**Comment by Ev1dentFir3** [comment]
At least I didn't blame rocket :-p
