### ISSUE TITLE
Invisible players on new build

### ISSUE THREAD

**Issue by JohnnyChimpo420** [RocketFoundation/Rocket#75]
I was having a problem with the beta build(I know there isn't supposed to be support for the beta because it is unstable), where i couldn't see any players, and when i was in /vanish they could see me...just something to check out maybe. I uninstalled rocket and am running vanilla right now and that solved the problem.

**Comment by h4ugen** [comment]
https://github.com/RocketFoundation/Rocket/issues/74

Confirmed

**Comment by manuelbarbosa** [comment]
Confirmed! I thought they where hacking and banned a few :p

**Comment by fr34kyn01535** [comment]
Haven't encountered this bug, the only prolem i saw so far is PvP/PvE

**Comment by h4ugen** [comment]
Same here manuel, so sorry about it too.
I was watching them forever, and I knew that hacking is literally impossible with VAC. But still banned a few.

Changing to vanilla will solve this temporarily.

**Comment by Zamirathe** [comment]
I helped someone else having this problem.  Turns out they were manually copying over files from their client Unturned folders to their server Unturned folders based on last change date.  They missed 1 file, and this bug happened.  Once he installed and used steamcmd with the validate in the command, his problem disappeared and so did this bug.

Please check to see if this was/is the case.
