### ISSUE TITLE
Bug with warnings!

### ISSUE THREAD

**Issue by 3HeavY0** [RocketFoundation/Rocket#93]
![2015-05-10_00002](https://cloud.githubusercontent.com/assets/12383380/7555297/624890a6-f74f-11e4-86e3-25ca335dd9b4.jpg)
I have update at 3.9.9.5 and it still send me this notes and when I enter in a server from Steam panel server it still show me that... ![2015-05-10_00003](https://cloud.githubusercontent.com/assets/12383380/7555314/54db58e4-f750-11e4-9765-cc1a7e9fcc10.jpg) I can play but those warnings appear for nothing. Why those notes still appears what time I can play on server and how can I make them to disappear?

**Comment by Zamirathe** [comment]
It is because it is playing with the server install of Steam.  You can't play with Rocket installed on the client.  It can be seen as a hack and get you VAC banned, which is why the message was installed.  You have to run your server under a separate instance of Unturned from the one you use to play.
